//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class u1400114_dbA9AEntities : DbContext
    {
        public u1400114_dbA9AEntities()
            : base("name=u1400114_dbA9AEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tbl_Admin> tbl_Admin { get; set; }
        public virtual DbSet<tbl_Arac> tbl_Arac { get; set; }
        public virtual DbSet<tbl_Aracturu> tbl_Aracturu { get; set; }
        public virtual DbSet<tbl_Ayarlar> tbl_Ayarlar { get; set; }
        public virtual DbSet<tbl_Blog> tbl_Blog { get; set; }
        public virtual DbSet<tbl_Hakkimizda> tbl_Hakkimizda { get; set; }
        public virtual DbSet<tbl_iletisim> tbl_iletisim { get; set; }
        public virtual DbSet<tbl_marka> tbl_marka { get; set; }
    }
}
