//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Admin
    {
        public int AdminID { get; set; }
        public string KullaniciAdin { get; set; }
        public string Sifre { get; set; }
    }
}
