//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Ayarlar
    {
        public int ID { get; set; }
        public Nullable<int> AltsayfaAdet { get; set; }
        public Nullable<int> AnasayfaAdet { get; set; }
        public string TelefonNo { get; set; }
        public string Mail { get; set; }
        public string Adres { get; set; }
        public string KısaAciklama { get; set; }
    }
}
