//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentaCar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Blog
    {
        public int ID { get; set; }
        public string Aciklama { get; set; }
        public string Baslik { get; set; }
        public System.DateTime Tarih { get; set; }
        public string BlogImage { get; set; }
        public Nullable<int> Onecikan { get; set; }
    }
}
